using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xFilm5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.OrderPkPrintQ.
    /// Date Created:   2016-11-13 09:13:54
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class OrderPkPrintQ
    {
        private int key = 0;
        private int orderPkPrintQId = 0;
        private int orderHeaderId = 0;
        private int printQueueId = 0;
        private int printQSubitemType = 0;
        private decimal qty;

        /// <summary>
        /// Initialize an new empty OrderPkPrintQ object.
        /// </summary>
        public OrderPkPrintQ()
        {
        }
		
        /// <summary>
        /// Initialize a new OrderPkPrintQ object with the given parameters.
        /// </summary>
        public OrderPkPrintQ(int orderPkPrintQId, int orderHeaderId, int printQueueId, int printQSubitemType, decimal qty)
        {
                this.orderPkPrintQId = orderPkPrintQId;
                this.orderHeaderId = orderHeaderId;
                this.printQueueId = printQueueId;
                this.printQSubitemType = printQSubitemType;
                this.qty = qty;
        }	
		
        /// <summary>
        /// Loads a OrderPkPrintQ object from the database using the given OrderPkPrintQId
        /// </summary>
        /// <param name="orderPkPrintQId">The primary key value</param>
        /// <returns>A OrderPkPrintQ object</returns>
        public static OrderPkPrintQ Load(int orderPkPrintQId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OrderPkPrintQId", orderPkPrintQId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spOrderPkPrintQ_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    OrderPkPrintQ result = new OrderPkPrintQ();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a OrderPkPrintQ object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A OrderPkPrintQ object</returns>
        public static OrderPkPrintQ LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spOrderPkPrintQ_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    OrderPkPrintQ result = new OrderPkPrintQ();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }
		
        /// <summary>
        /// Loads a collection of OrderPkPrintQ objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderPkPrintQ objects in the database.</returns>
        public static OrderPkPrintQCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] {};
            return LoadCollection("spOrderPkPrintQ_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderPkPrintQ objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the OrderPkPrintQ objects in the database ordered by the columns specified.</returns>
        public static OrderPkPrintQCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spOrderPkPrintQ_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderPkPrintQ objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderPkPrintQ objects in the database.</returns>
        public static OrderPkPrintQCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spOrderPkPrintQ_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderPkPrintQ objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the OrderPkPrintQ objects in the database ordered by the columns specified.</returns>
        public static OrderPkPrintQCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spOrderPkPrintQ_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of OrderPkPrintQ objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the OrderPkPrintQ objects in the database.</returns>
        public static OrderPkPrintQCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            OrderPkPrintQCollection result = new OrderPkPrintQCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    OrderPkPrintQ tmp = new OrderPkPrintQ();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a OrderPkPrintQ object from the database.
        /// </summary>
        /// <param name="orderPkPrintQId">The primary key value</param>
        public static void Delete(int orderPkPrintQId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@OrderPkPrintQId", orderPkPrintQId) };
            SqlHelper.Default.ExecuteNonQuery("spOrderPkPrintQ_DelRec", parameterValues);
        }

		
        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetInt32(0);
                if (!reader.IsDBNull(0)) orderPkPrintQId = reader.GetInt32(0);
                if (!reader.IsDBNull(1)) orderHeaderId = reader.GetInt32(1);
                if (!reader.IsDBNull(2)) printQueueId = reader.GetInt32(2);
                if (!reader.IsDBNull(3)) printQSubitemType = reader.GetInt32(3);
                if (!reader.IsDBNull(4)) qty = reader.GetDecimal(4);
            }
        }
		
        public void Delete()
        {
            Delete(this.OrderPkPrintQId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == 0)
                Insert();
            else
            {
                if (key != OrderPkPrintQId)
                    this.Delete();
                Update();
            }
        }

        public int OrderPkPrintQId
        {
            get { return orderPkPrintQId; }
            set { orderPkPrintQId = value; }
        }

        public int OrderHeaderId
        {
            get { return orderHeaderId; }
            set { orderHeaderId = value; }
        }

        public int PrintQueueId
        {
            get { return printQueueId; }
            set { printQueueId = value; }
        }

        public int PrintQSubitemType
        {
            get { return printQSubitemType; }
            set { printQSubitemType = value; }
        }

        public decimal Qty
        {
            get { return qty; }
            set { qty = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;
			
            SqlHelper.Default.ExecuteNonQuery("spOrderPkPrintQ_InsRec", "@OrderPkPrintQId", out returnedValue, parameterValues);
            
            orderPkPrintQId = returnedValue != null ? (int)returnedValue : 0;
            key = returnedValue != null ? (int)returnedValue : 0;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();
            
			SqlHelper.Default.ExecuteNonQuery("spOrderPkPrintQ_UpdRec", parameterValues);
        }
        
        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[5];
            prams[0] = GetSqlParameter("@OrderPkPrintQId", ParameterDirection.Output, SqlDbType.Int, 4, this.OrderPkPrintQId);
            prams[1] = GetSqlParameter("@OrderHeaderId", ParameterDirection.Input, SqlDbType.Int, 4, this.OrderHeaderId);
            prams[2] = GetSqlParameter("@PrintQueueId", ParameterDirection.Input, SqlDbType.Int, 4, this.PrintQueueId);
            prams[3] = GetSqlParameter("@PrintQSubitemType", ParameterDirection.Input, SqlDbType.Int, 4, this.PrintQSubitemType);
            prams[4] = GetSqlParameter("@Qty", ParameterDirection.Input, SqlDbType.Decimal, 9, this.Qty);
            return prams;
        }
		
        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }
        
        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[] 
            {
                GetSqlParameterWithoutDirection("@OrderPkPrintQId", SqlDbType.Int, 4, this.OrderPkPrintQId),
                GetSqlParameterWithoutDirection("@OrderHeaderId", SqlDbType.Int, 4, this.OrderHeaderId),
                GetSqlParameterWithoutDirection("@PrintQueueId", SqlDbType.Int, 4, this.PrintQueueId),
                GetSqlParameterWithoutDirection("@PrintQSubitemType", SqlDbType.Int, 4, this.PrintQSubitemType),
                GetSqlParameterWithoutDirection("@Qty", SqlDbType.Decimal, 9, this.Qty)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("orderPkPrintQId: " + orderPkPrintQId.ToString()).Append("\r\n");
            builder.Append("orderHeaderId: " + orderHeaderId.ToString()).Append("\r\n");
            builder.Append("printQueueId: " + printQueueId.ToString()).Append("\r\n");
            builder.Append("printQSubitemType: " + printQSubitemType.ToString()).Append("\r\n");
            builder.Append("qty: " + qty.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }	
		
		#region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[]{ TextField });
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			string [] textField = {TextField};
			LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			if (SwitchLocale)
			{
				TextField = GetSwitchLocale(TextField);
			}
			ddList.Items.Clear();						
			
			OrderPkPrintQCollection source;
            
            if(OrderBy == null || OrderBy.Length == 0)
            {
			    OrderBy = TextField;
            }
			
			if (WhereClause.Length > 0)
			{
				source = OrderPkPrintQ.LoadCollection(WhereClause, OrderBy, true);
			}
			else
			{
				source = OrderPkPrintQ.LoadCollection(OrderBy, true);
			}
			
            Common.ComboList sourceList = new Common.ComboList();

			if (BlankLine)
			{
                sourceList.Add(new Common.ComboItem(BlankLineText, 0));
			}
			
			foreach (OrderPkPrintQ item in source)
			{
				bool filter = false;
				if (ParentFilter.Trim() != String.Empty)
				{
					filter = true;
					if (item.OrderHeaderId != 0)
					{
						filter = IgnorThis(item, ParentFilter);
					}
				}
				if (!(filter))
				{
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.OrderPkPrintQId));
				}
			}			

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";
			
			if (ddList.Items.Count > 0)
			{
			    ddList.SelectedIndex = 0;
            }
		}
		
		#endregion
		
		
		private static bool IgnorThis(OrderPkPrintQ target, string parentFilter)
		{
			bool result = true;
			parentFilter = parentFilter.Replace(" ", "");		// remove spaces
			parentFilter = parentFilter.Replace("'", "");		// remove '
			string [] parsed = parentFilter.Split('=');			// parse

			if (target.OrderHeaderId == 0)
			{
				PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
				string filterField = (string)pi.GetValue(target, null);
				if (filterField.ToLower() == parsed[1].ToLower())
				{
					result = false;
				}
			}
			else
			{
				OrderPkPrintQ parentTemplate = OrderPkPrintQ.Load(target.OrderHeaderId);
				result = IgnorThis(parentTemplate, parentFilter);
			}
			return result;
		}

		private static string GetFormatedText(OrderPkPrintQ target, string [] textField, string textFormatString)
		{
			for (int i = 0; i < textField.Length; i++)
			{
				PropertyInfo pi = target.GetType().GetProperty(textField[i]);
				textFormatString = textFormatString.Replace("{" + i.ToString() +"}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
			}
			return textFormatString;
		}
		
		private static string [] GetSwitchLocale(string [] source)
		{
			switch (Common.Config.CurrentLanguageId)
			{
				case 2:
					source[source.Length - 1] += "_Chs";
					break;
				case 3:
					source[source.Length - 1] += "_Cht";
					break;
			}
			return source;
		}
    }


    /// <summary>
    /// Represents a collection of <see cref="OrderPkPrintQ">OrderPkPrintQ</see> objects.
    /// </summary>
    public class OrderPkPrintQCollection : BindingList< OrderPkPrintQ>
    {
	}
}
