using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace xFilm5.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.PosTx.
    /// Date Created:   2016-06-25 12:48:18
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class PosTx
    {
        private int key = 0;
        private int txID = 0;
        private DateTime txDate = DateTime.Parse("1900-1-1");
        private int branch = 0;
        private int txPosID = 0;
        private int txType = 0;
        private string txRef = String.Empty;
        private decimal txAmount;
        private int txAmountType = 0;
        private int createdBy = 0;
        private string remarks = String.Empty;

        /// <summary>
        /// Initialize an new empty PosTx object.
        /// </summary>
        public PosTx()
        {
        }

        /// <summary>
        /// Initialize a new PosTx object with the given parameters.
        /// </summary>
        public PosTx(int txID, DateTime txDate, int branch, int txPosID, int txType, string txRef, decimal txAmount, int txAmountType, int createdBy, string remarks)
        {
            this.txID = txID;
            this.txDate = txDate;
            this.branch = branch;
            this.txPosID = txPosID;
            this.txType = txType;
            this.txRef = txRef;
            this.txAmount = txAmount;
            this.txAmountType = txAmountType;
            this.createdBy = createdBy;
            this.remarks = remarks;
        }

        /// <summary>
        /// Loads a PosTx object from the database using the given TxID
        /// </summary>
        /// <param name="txID">The primary key value</param>
        /// <returns>A PosTx object</returns>
        public static PosTx Load(int txID)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@TxID", txID) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spPosTx_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    PosTx result = new PosTx();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a PosTx object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A PosTx object</returns>
        public static PosTx LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spPosTx_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    PosTx result = new PosTx();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a collection of PosTx objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the PosTx objects in the database.</returns>
        public static PosTxCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] { };
            return LoadCollection("spPosTx_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of PosTx objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the PosTx objects in the database ordered by the columns specified.</returns>
        public static PosTxCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spPosTx_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of PosTx objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the PosTx objects in the database.</returns>
        public static PosTxCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spPosTx_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of PosTx objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the PosTx objects in the database ordered by the columns specified.</returns>
        public static PosTxCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length - 1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spPosTx_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of PosTx objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the PosTx objects in the database.</returns>
        public static PosTxCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            PosTxCollection result = new PosTxCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    PosTx tmp = new PosTx();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a PosTx object from the database.
        /// </summary>
        /// <param name="txID">The primary key value</param>
        public static void Delete(int txID)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@TxID", txID) };
            SqlHelper.Default.ExecuteNonQuery("spPosTx_DelRec", parameterValues);
        }


        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetInt32(0);
                if (!reader.IsDBNull(0)) txID = reader.GetInt32(0);
                if (!reader.IsDBNull(1)) txDate = reader.GetDateTime(1);
                if (!reader.IsDBNull(2)) branch = reader.GetInt32(2);
                if (!reader.IsDBNull(3)) txPosID = reader.GetInt32(3);
                if (!reader.IsDBNull(4)) txType = reader.GetInt32(4);
                if (!reader.IsDBNull(5)) txRef = reader.GetString(5);
                if (!reader.IsDBNull(6)) txAmount = reader.GetDecimal(6);
                if (!reader.IsDBNull(7)) txAmountType = reader.GetInt32(7);
                if (!reader.IsDBNull(8)) createdBy = reader.GetInt32(8);
                if (!reader.IsDBNull(9)) remarks = reader.GetString(9);
            }
        }

        public void Delete()
        {
            Delete(this.TxID);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == 0)
                Insert();
            else
            {
                if (key != TxID)
                    this.Delete();
                Update();
            }
        }

        public int TxID
        {
            get { return txID; }
            set { txID = value; }
        }

        public DateTime TxDate
        {
            get { return txDate; }
            set { txDate = value; }
        }

        public int Branch
        {
            get { return branch; }
            set { branch = value; }
        }

        public int TxPosID
        {
            get { return txPosID; }
            set { txPosID = value; }
        }

        public int TxType
        {
            get { return txType; }
            set { txType = value; }
        }

        public string TxRef
        {
            get { return txRef; }
            set { txRef = value; }
        }

        public decimal TxAmount
        {
            get { return txAmount; }
            set { txAmount = value; }
        }

        public int TxAmountType
        {
            get { return txAmountType; }
            set { txAmountType = value; }
        }

        public int CreatedBy
        {
            get { return createdBy; }
            set { createdBy = value; }
        }

        public string Remarks
        {
            get { return remarks; }
            set { remarks = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;

            SqlHelper.Default.ExecuteNonQuery("spPosTx_InsRec", "@TxID", out returnedValue, parameterValues);

            txID = returnedValue != null ? (int)returnedValue : 0;
            key = returnedValue != null ? (int)returnedValue : 0;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();

            SqlHelper.Default.ExecuteNonQuery("spPosTx_UpdRec", parameterValues);
        }

        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[10];
            prams[0] = GetSqlParameter("@TxID", ParameterDirection.Output, SqlDbType.Int, 4, this.TxID);
            prams[1] = GetSqlParameter("@TxDate", ParameterDirection.Input, SqlDbType.DateTime, 8, this.TxDate);
            prams[2] = GetSqlParameter("@Branch", ParameterDirection.Input, SqlDbType.Int, 4, this.Branch);
            prams[3] = GetSqlParameter("@TxPosID", ParameterDirection.Input, SqlDbType.Int, 4, this.TxPosID);
            prams[4] = GetSqlParameter("@TxType", ParameterDirection.Input, SqlDbType.Int, 4, this.TxType);
            prams[5] = GetSqlParameter("@TxRef", ParameterDirection.Input, SqlDbType.NVarChar, 32, this.TxRef);
            prams[6] = GetSqlParameter("@TxAmount", ParameterDirection.Input, SqlDbType.Money, 8, this.TxAmount);
            prams[7] = GetSqlParameter("@TxAmountType", ParameterDirection.Input, SqlDbType.Int, 4, this.TxAmountType);
            prams[8] = GetSqlParameter("@CreatedBy", ParameterDirection.Input, SqlDbType.Int, 4, this.CreatedBy);
            prams[9] = GetSqlParameter("@Remarks", ParameterDirection.Input, SqlDbType.NVarChar, 256, this.Remarks);
            return prams;
        }

        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }

        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[]
            {
                GetSqlParameterWithoutDirection("@TxID", SqlDbType.Int, 4, this.TxID),
                GetSqlParameterWithoutDirection("@TxDate", SqlDbType.DateTime, 8, this.TxDate),
                GetSqlParameterWithoutDirection("@Branch", SqlDbType.Int, 4, this.Branch),
                GetSqlParameterWithoutDirection("@TxPosID", SqlDbType.Int, 4, this.TxPosID),
                GetSqlParameterWithoutDirection("@TxType", SqlDbType.Int, 4, this.TxType),
                GetSqlParameterWithoutDirection("@TxRef", SqlDbType.NVarChar, 32, this.TxRef),
                GetSqlParameterWithoutDirection("@TxAmount", SqlDbType.Money, 8, this.TxAmount),
                GetSqlParameterWithoutDirection("@TxAmountType", SqlDbType.Int, 4, this.TxAmountType),
                GetSqlParameterWithoutDirection("@CreatedBy", SqlDbType.Int, 4, this.CreatedBy),
                GetSqlParameterWithoutDirection("@Remarks", SqlDbType.NVarChar, 256, this.Remarks)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("txID: " + txID.ToString()).Append("\r\n");
            builder.Append("txDate: " + txDate.ToString()).Append("\r\n");
            builder.Append("branch: " + branch.ToString()).Append("\r\n");
            builder.Append("txPosID: " + txPosID.ToString()).Append("\r\n");
            builder.Append("txType: " + txType.ToString()).Append("\r\n");
            builder.Append("txRef: " + txRef.ToString()).Append("\r\n");
            builder.Append("txAmount: " + txAmount.ToString()).Append("\r\n");
            builder.Append("txAmountType: " + txAmountType.ToString()).Append("\r\n");
            builder.Append("createdBy: " + createdBy.ToString()).Append("\r\n");
            builder.Append("remarks: " + remarks.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }

        #region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            string[] textField = { TextField };
            LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
        {
            LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
        }

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
        public static void LoadCombo(ref ComboBox ddList, string[] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
        {
            if (SwitchLocale)
            {
                TextField = GetSwitchLocale(TextField);
            }
            ddList.Items.Clear();

            PosTxCollection source;

            if (OrderBy == null || OrderBy.Length == 0)
            {
                OrderBy = TextField;
            }

            if (WhereClause.Length > 0)
            {
                source = PosTx.LoadCollection(WhereClause, OrderBy, true);
            }
            else
            {
                source = PosTx.LoadCollection(OrderBy, true);
            }

            Common.ComboList sourceList = new Common.ComboList();

            if (BlankLine)
            {
                sourceList.Add(new Common.ComboItem(BlankLineText, 0));
            }

            foreach (PosTx item in source)
            {
                bool filter = false;
                if (ParentFilter.Trim() != String.Empty)
                {
                    filter = IgnorThis(item, ParentFilter);
                }
                if (!(filter))
                {
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.TxID));
                }
            }

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";

            if (ddList.Items.Count > 0)
            {
                ddList.SelectedIndex = 0;
            }
        }

        #endregion


        private static bool IgnorThis(PosTx target, string parentFilter)
        {
            bool result = true;
            parentFilter = parentFilter.Replace(" ", "");       // remove spaces
            parentFilter = parentFilter.Replace("'", "");       // remove '
            string[] parsed = parentFilter.Split('=');          // parse

            PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
            string filterField = (string)pi.GetValue(target, null);
            if (filterField.ToLower() == parsed[1].ToLower())
            {
                result = false;
            }
            return result;
        }

        private static string GetFormatedText(PosTx target, string[] textField, string textFormatString)
        {
            for (int i = 0; i < textField.Length; i++)
            {
                PropertyInfo pi = target.GetType().GetProperty(textField[i]);
                textFormatString = textFormatString.Replace("{" + i.ToString() + "}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
            }
            return textFormatString;
        }

        private static string[] GetSwitchLocale(string[] source)
        {
            switch (Common.Config.CurrentLanguageId)
            {
                case 2:
                    source[source.Length - 1] += "_Chs";
                    break;
                case 3:
                    source[source.Length - 1] += "_Cht";
                    break;
            }
            return source;
        }
    }


    /// <summary>
    /// Represents a collection of <see cref="PosTx">PosTx</see> objects.
    /// </summary>
    public class PosTxCollection : BindingList<PosTx>
    {
    }
}
