//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFilm5.Bot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPkPrintQ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderPkPrintQ()
        {
            this.Acct_INDetails = new HashSet<Acct_INDetails>();
            this.ReceiptDetails = new HashSet<ReceiptDetail>();
        }
    
        public int OrderPkPrintQId { get; set; }
        public int OrderHeaderId { get; set; }
        public int PrintQueueId { get; set; }
        public int PrintQSubitemType { get; set; }
        public decimal Qty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acct_INDetails> Acct_INDetails { get; set; }
        public virtual OrderHeader OrderHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptDetail> ReceiptDetails { get; set; }
        public virtual PrintQueue PrintQueue { get; set; }
    }
}
