//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFilm5.Bot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintQueue_VPS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrintQueue_VPS()
        {
            this.OrderPkPrintQueueVps = new HashSet<OrderPkPrintQueueVps>();
            this.PrintQueue_LifeCycle = new HashSet<PrintQueue_LifeCycle>();
        }
    
        public int ID { get; set; }
        public int PrintQueueID { get; set; }
        public string VpsFileName { get; set; }
        public bool PlateOrdered { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> Retired { get; set; }
        public System.DateTime RetiredOn { get; set; }
        public Nullable<int> RetiredBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPkPrintQueueVps> OrderPkPrintQueueVps { get; set; }
        public virtual PrintQueue PrintQueue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrintQueue_LifeCycle> PrintQueue_LifeCycle { get; set; }
    }
}
