//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFilm5.Bot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BillingCode_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_BillingCode_Item()
        {
            this.ClientPricing = new HashSet<ClientPricing>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string ItemCode { get; set; }
        public string GroupCode { get; set; }
        public string Name { get; set; }
        public string UoM { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public bool Retired { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPricing> ClientPricing { get; set; }
        public virtual T_BillingCode_Dept T_BillingCode_Dept { get; set; }
    }
}
