//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFilm5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acct_INDetails
    {
        public int ID { get; set; }
        public int INMasterID { get; set; }
        public Nullable<int> OrderPkPrintQueueVpsId { get; set; }
        public string BillingCode { get; set; }
        public string Description { get; set; }
        public Nullable<short> Qty { get; set; }
        public Nullable<decimal> UnitAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Acct_INMaster Acct_INMaster { get; set; }
        public virtual OrderPkPrintQueueVps OrderPkPrintQueueVps { get; set; }
    }
}
