//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFilm5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCMHistory
    {
        public int FCMHistoryId { get; set; }
        public string MessageTitle { get; set; }
        public string MessageBody { get; set; }
        public System.DateTime DeliveredOn { get; set; }
        public string Topic { get; set; }
        public string RecipientList { get; set; }
        public string UserIdList { get; set; }
    }
}
