//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFilm5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPkPrintQueueVps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderPkPrintQueueVps()
        {
            this.Acct_INDetails = new HashSet<Acct_INDetails>();
            this.ReceiptDetail = new HashSet<ReceiptDetail>();
        }
    
        public int OrderPkPrintQueueVpsId { get; set; }
        public Nullable<int> OrderHeaderId { get; set; }
        public Nullable<int> PrintQueueVpsId { get; set; }
        public bool CheckedPlate { get; set; }
        public bool CheckedCip3 { get; set; }
        public bool CheckedBlueprint { get; set; }
        public bool IsReady { get; set; }
        public bool IsReceived { get; set; }
        public bool IsBilled { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool Retired { get; set; }
        public Nullable<System.DateTime> RetiredOn { get; set; }
        public Nullable<int> RetiredBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acct_INDetails> Acct_INDetails { get; set; }
        public virtual OrderHeader OrderHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptDetail> ReceiptDetail { get; set; }
        public virtual PrintQueue_VPS PrintQueue_VPS { get; set; }
    }
}
