//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFilm5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SoftwareVersion
    {
        public int ID { get; set; }
        public int SoftwareID { get; set; }
        public string VersionNumber { get; set; }
    
        public virtual T_Software T_Software { get; set; }
    }
}
