//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFilm5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreference
    {
        public int PreferenceId { get; set; }
        public int UserId { get; set; }
        public System.Guid ObjectId { get; set; }
        public int ObjectType { get; set; }
        public string MetadataXml { get; set; }
    
        public virtual User User { get; set; }
    }
}
