//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFilm5.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClientUserList
    {
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<short> CreditLimit { get; set; }
        public Nullable<short> PaymentTerms { get; set; }
        public Nullable<short> PaymentType { get; set; }
        public string PIN { get; set; }
        public int UserId { get; set; }
        public bool PrimaryUser { get; set; }
        public string UserFullName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<short> SecurityLevel { get; set; }
        public string Email { get; set; }
    }
}
